
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        <main className="containter mx-auto px-4 md:pz-8 py-4">
          <section className="flex flex-col md:flex-row md:space-x-6 justify-center items-center">
            {children}
          </section>

        </main>
      </body>
    </html>
  )
}